const fs = require('fs');
let code = fs.readFileSync('src/components/VitroModal.tsx', 'utf8');

const nameplates = `const NAMEPLATES = [
  { name: "Goofy Happy Tune", filename: "https://raw.githubusercontent.com/nyatter1/usercards/main/goofy_happy_tune.webm" },
  { name: "Gothic Arches", filename: "https://raw.githubusercontent.com/nyatter1/usercards/main/gothic_arches.webm" },
  { name: "Green Mana", filename: "https://raw.githubusercontent.com/nyatter1/usercards/main/green_mana.webm" },
  { name: "Grogu", filename: "https://raw.githubusercontent.com/nyatter1/usercards/main/grogu.webm" },
  { name: "Gudetama", filename: "https://raw.githubusercontent.com/nyatter1/usercards/main/gudetama.webm" },
  { name: "Haiti", filename: "https://raw.githubusercontent.com/nyatter1/usercards/main/haiti.webm" },
  { name: "Heart's Reflection", filename: "https://raw.githubusercontent.com/nyatter1/usercards/main/heart%27s_reflection.webm" },
  { name: "Hello Kitty", filename: "https://raw.githubusercontent.com/nyatter1/usercards/main/hello_kitty.webm" },
  { name: "Hermit's Lantern", filename: "https://raw.githubusercontent.com/nyatter1/usercards/main/hermit%27s_lantern.webm" },
  { name: "Hoppy Boi's Perch", filename: "https://raw.githubusercontent.com/nyatter1/usercards/main/hoppy_boi%27s_perch.webm" },
  { name: "Hot Dog", filename: "https://raw.githubusercontent.com/nyatter1/usercards/main/hot_dog.webm" },
  { name: "Hunny Bunnies", filename: "https://raw.githubusercontent.com/nyatter1/usercards/main/hunny_bunnies.webm" },
  { name: "Hyperspace", filename: "https://raw.githubusercontent.com/nyatter1/usercards/main/hyperspace.webm" },
  { name: "Ichi Nyan", filename: "https://raw.githubusercontent.com/nyatter1/usercards/main/ichi_nyan.webm" },
  { name: "Infinite Swirl", filename: "https://raw.githubusercontent.com/nyatter1/usercards/main/infinite_swirl.webm" },
  { name: "Iran", filename: "https://raw.githubusercontent.com/nyatter1/usercards/main/iran.webm" },
  { name: "Iraq", filename: "https://raw.githubusercontent.com/nyatter1/usercards/main/iraq.webm" },
  { name: "Japan", filename: "https://raw.githubusercontent.com/nyatter1/usercards/main/japan.webm" },
  { name: "Jordan", filename: "https://raw.githubusercontent.com/nyatter1/usercards/main/jordan.webm" },
  { name: "K Heart (Base)", filename: "https://raw.githubusercontent.com/nyatter1/usercards/main/k_heart_%28base%29.webm" },
  { name: "K Heart (Dark)", filename: "https://raw.githubusercontent.com/nyatter1/usercards/main/k_heart_%28dark%29.webm" },
  { name: "K Heart (Light)", filename: "https://raw.githubusercontent.com/nyatter1/usercards/main/k_heart_%28light%29.webm" },
  { name: "K Heart (Medium)", filename: "https://raw.githubusercontent.com/nyatter1/usercards/main/k_heart_%28medium%29.webm" },
  { name: "Koi Pond", filename: "https://raw.githubusercontent.com/nyatter1/usercards/main/koi_pond.webm" },
  { name: "Kuromi x My Melody", filename: "https://raw.githubusercontent.com/nyatter1/usercards/main/kuromi_x_my_melody.webm" },
  { name: "Ladybug Lulau", filename: "https://raw.githubusercontent.com/nyatter1/usercards/main/ladybug_lulau.webm" },
  { name: "Leo", filename: "https://raw.githubusercontent.com/nyatter1/usercards/main/leo.webm" },
  { name: "Red Dragon", filename: "https://raw.githubusercontent.com/nyatter1/usercards/main/red_dragon.webm" },
  { name: "Red Mana", filename: "https://raw.githubusercontent.com/nyatter1/usercards/main/red_mana.webm" },
  { name: "Ripper Awakens", filename: "https://raw.githubusercontent.com/nyatter1/usercards/main/ripper_awakens.webm" },
  { name: "Roly Roly (Blue)", filename: "https://raw.githubusercontent.com/nyatter1/usercards/main/roly_roly_%28blue%29.webm" },
  { name: "Roly Roly (Orange)", filename: "https://raw.githubusercontent.com/nyatter1/usercards/main/roly_roly_%28orange%29.webm" },
  { name: "Roly Roly (Pink)", filename: "https://raw.githubusercontent.com/nyatter1/usercards/main/roly_roly_%28pink%29.webm" },
  { name: "Ryomen Sukuna", filename: "https://raw.githubusercontent.com/nyatter1/usercards/main/ryomen_sukuna.webm" },
  { name: "Sagittarius", filename: "https://raw.githubusercontent.com/nyatter1/usercards/main/sagittarius.webm" },
  { name: "Satoru Gojo", filename: "https://raw.githubusercontent.com/nyatter1/usercards/main/satoru_gojo.webm" },
  { name: "Saudi Arabia", filename: "https://raw.githubusercontent.com/nyatter1/usercards/main/saudi_arabia.webm" },
  { name: "Scorpio", filename: "https://raw.githubusercontent.com/nyatter1/usercards/main/scorpio.webm" },
  { name: "Scotland", filename: "https://raw.githubusercontent.com/nyatter1/usercards/main/scotland.webm" },
  { name: "Secret Agent", filename: "https://raw.githubusercontent.com/nyatter1/usercards/main/secrect_agent.webm" },
  { name: "Senegal", filename: "https://raw.githubusercontent.com/nyatter1/usercards/main/senegal.webm" },
  { name: "Shattered Veil", filename: "https://raw.githubusercontent.com/nyatter1/usercards/main/shattered_veil.webm" },
  { name: "Skibidi Toilet", filename: "https://raw.githubusercontent.com/nyatter1/usercards/main/skibidi_toilet.webm" },
  { name: "South Africa", filename: "https://raw.githubusercontent.com/nyatter1/usercards/main/south_africa.webm" },
  { name: "South America", filename: "https://raw.githubusercontent.com/nyatter1/usercards/main/south_america.webm" },
  { name: "South Korea", filename: "https://raw.githubusercontent.com/nyatter1/usercards/main/south_korea.webm" },
  { name: "Spain", filename: "https://raw.githubusercontent.com/nyatter1/usercards/main/spain.webm" },
  { name: "Spider-Man (Logo)", filename: "https://raw.githubusercontent.com/nyatter1/usercards/main/spider-man_%28logo%29.webm" },
  { name: "Spider-Man (No Logo)", filename: "https://raw.githubusercontent.com/nyatter1/usercards/main/spider-man_%28no_logo%29.webm" },
  { name: "Spider-Man vs Venom", filename: "https://raw.githubusercontent.com/nyatter1/usercards/main/spider-man_vs_venom.webm" },
  { name: "Spirit Blossom Petrals", filename: "https://raw.githubusercontent.com/nyatter1/usercards/main/spirit_blossom_petrals.webm" },
  { name: "Spirit Blossom Springs", filename: "https://raw.githubusercontent.com/nyatter1/usercards/main/spirit_blossom_springs.webm" },
  { name: "Spirit Moon", filename: "https://raw.githubusercontent.com/nyatter1/usercards/main/spirit_moon.webm" },
  { name: "Spirit of Spring", filename: "https://raw.githubusercontent.com/nyatter1/usercards/main/spirit_of_spring.webm" },
  { name: "Spray Doodles", filename: "https://raw.githubusercontent.com/nyatter1/usercards/main/spray_doodles.webm" },
  { name: "Sproutling", filename: "https://raw.githubusercontent.com/nyatter1/usercards/main/sproutling.webm" },
  { name: "Squad Wipe", filename: "https://raw.githubusercontent.com/nyatter1/usercards/main/squad_wipe.webm" },
  { name: "Star Drift", filename: "https://raw.githubusercontent.com/nyatter1/usercards/main/star_drift.webm" },
  { name: "Star Struck", filename: "https://raw.githubusercontent.com/nyatter1/usercards/main/star_struck.webm" },
  { name: "Starfall Tides", filename: "https://raw.githubusercontent.com/nyatter1/usercards/main/starfall_tides.webm" },
  { name: "Starfall Tides (Nightshade)", filename: "https://raw.githubusercontent.com/nyatter1/usercards/main/starfall_tides_%28Nightshade%29.webm" },
  { name: "Starfall Tides (Rose)", filename: "https://raw.githubusercontent.com/nyatter1/usercards/main/starfall_tides_%28rose%29.webm" },
  { name: "Starfall Tides (Void)", filename: "https://raw.githubusercontent.com/nyatter1/usercards/main/starfall_tides_%28void%29.webm" },
  { name: "Starlight Whales", filename: "https://raw.githubusercontent.com/nyatter1/usercards/main/starlight_whales.webm" },
  { name: "Sub Saharan Africa", filename: "https://raw.githubusercontent.com/nyatter1/usercards/main/sub_saharan_africa.webm" },
  { name: "Sun and Moon", filename: "https://raw.githubusercontent.com/nyatter1/usercards/main/sun_and_moon.webm" },
  { name: "Sunlit Radiance", filename: "https://raw.githubusercontent.com/nyatter1/usercards/main/sunlit_radiance.webm" },
  { name: "Sweden", filename: "https://raw.githubusercontent.com/nyatter1/usercards/main/sweden.webm" },
  { name: "Sweetheart Charm", filename: "https://raw.githubusercontent.com/nyatter1/usercards/main/sweetheart_charm.webm" },
  { name: "Switzerland", filename: "https://raw.githubusercontent.com/nyatter1/usercards/main/switzerland.webm" },
  { name: "Sword of Legend", filename: "https://raw.githubusercontent.com/nyatter1/usercards/main/sword_of_legend.webm" },
  { name: "Taurus", filename: "https://raw.githubusercontent.com/nyatter1/usercards/main/taurus.webm" },
  { name: "The Clawww", filename: "https://raw.githubusercontent.com/nyatter1/usercards/main/the_clawww.webm" },
  { name: "The Grid Fireworks", filename: "https://raw.githubusercontent.com/nyatter1/usercards/main/the_grid_fireworks.webm" },
  { name: "The Same Duck", filename: "https://raw.githubusercontent.com/nyatter1/usercards/main/the_same_duck.webm" },
  { name: "Toasty", filename: "https://raw.githubusercontent.com/nyatter1/usercards/main/toasty.webm" },
  { name: "Touch Grass", filename: "https://raw.githubusercontent.com/nyatter1/usercards/main/touch_grass.webm" },
  { name: "Tower's Strike", filename: "https://raw.githubusercontent.com/nyatter1/usercards/main/tower%27s_strike.webm" },
  { name: "Tunisia", filename: "https://raw.githubusercontent.com/nyatter1/usercards/main/tunisia.webm" },
  { name: "Turkey", filename: "https://raw.githubusercontent.com/nyatter1/usercards/main/turkey.webm" },
  { name: "TV Woman", filename: "https://raw.githubusercontent.com/nyatter1/usercards/main/tv_woman.webm" },
  { name: "Twilight", filename: "https://raw.githubusercontent.com/nyatter1/usercards/main/twilight.webm" },
  { name: "Twilight (Dusk)", filename: "https://raw.githubusercontent.com/nyatter1/usercards/main/twilight_%28dusk%29.webm" },
  { name: "Twilight (Fuchsia)", filename: "https://raw.githubusercontent.com/nyatter1/usercards/main/twilight_%28fuchsia%29.webm" },
  { name: "Under The Sea", filename: "https://raw.githubusercontent.com/nyatter1/usercards/main/under_the_sea.webm" },
  { name: "United States", filename: "https://raw.githubusercontent.com/nyatter1/usercards/main/united_states.webm" },
  { name: "Uruguay", filename: "https://raw.githubusercontent.com/nyatter1/usercards/main/uruguay.webm" },
  { name: "Uzbekistan", filename: "https://raw.githubusercontent.com/nyatter1/usercards/main/uzbekistan.webm" },
  { name: "Vault", filename: "https://raw.githubusercontent.com/nyatter1/usercards/main/vault.webm" },
  { name: "Vengeance", filename: "https://raw.githubusercontent.com/nyatter1/usercards/main/vengeance.webm" },
  { name: "Venom (Logo)", filename: "https://raw.githubusercontent.com/nyatter1/usercards/main/venom_%28logo%29.webm" },
  { name: "Venom (No Logo)", filename: "https://raw.githubusercontent.com/nyatter1/usercards/main/venom_%28no_logo%29.webm" },
  { name: "Virgo", filename: "https://raw.githubusercontent.com/nyatter1/usercards/main/virgo.webm" },
  { name: "Western Europe", filename: "https://raw.githubusercontent.com/nyatter1/usercards/main/western_europe.webm" },
  { name: "White Mana", filename: "https://raw.githubusercontent.com/nyatter1/usercards/main/white_mana.webm" },
  { name: "Woodsprite", filename: "https://raw.githubusercontent.com/nyatter1/usercards/main/woodsprite.webm" },
  { name: "Woody's Badge", filename: "https://raw.githubusercontent.com/nyatter1/usercards/main/woody%27s_badge.webm" },
  { name: "Yoda", filename: "https://raw.githubusercontent.com/nyatter1/usercards/main/yoda.webm" },
  { name: "Yuji Itadori", filename: "https://raw.githubusercontent.com/nyatter1/usercards/main/yuji_itadori.webm" },
  { name: "Yunara's Aion Er'na", filename: "https://raw.githubusercontent.com/nyatter1/usercards/main/yunara%27s_aion_er%27na.webm" }
];\n`;

code = code.replace(/const CATEGORIES = \["All", "Cats \& Dogs", "Futuristic", "Nature \& Cute", "Orbiting \& FX"\];/, nameplates + 'const CATEGORIES = ["All", "Cats & Dogs", "Futuristic", "Nature & Cute", "Orbiting & FX"];');
fs.writeFileSync('src/components/VitroModal.tsx', code);
